### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by u12206050** [motze92/office365-mail#18]
Client error: `POST https://login.microsoftonline.com//oauth2/v2.0/token` resulted in a `404 Not Found` response

**Comment by michaelmannucci** [comment]
Got the same thing. I guess no solution :/

**Comment by matrad** [comment]
Are you behind a Proxy?
Can you set a Breakpoint where the Exception is thrown and Post here the full response-Body of the 404 not Found response?

**Comment by wbianchini** [comment]
I recently came to this driver and had this error.

If anyone still having this issue, the provider uses a configuration file to read the environment variables, so you must have the  office365mail.php under the config directory.

So its important to publish using `php  artisan  vendor:publish  --tag=office365mail` or create this file

**Comment by InWave** [comment]
I had the same problem on my production server, not on my dev environment. My config file office365mail was published. 
When I checked in Tinker with: config()->all(); this was the output:

`
"office365mail" => [
       "client_id" => null,
       "tenant" => null,
       "client_secret" => null,
     ],
`

After a second php artisan config:clear I could see the values in Tinker. Which is strange because in my deployment proces this command is already called. Hope this helps someone to debug (and my problem is gone for good....)

**Comment by motze92** [comment]
It must be something with your config, Because after `https://login.microsoftonline.com/` comes your office365mail->tenant config value and if this is null you get `https://login.microsoftonline.com//oauth2/v2.0/token`
